version: '3' 

services: 
    log:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes: # again text.log must exist within the host machine
        - ./text.log:/usr/src/app/text.log