FROM golang:alpine AS build-stage

WORKDIR /usr/src/app

COPY . .

RUN go build

FROM alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/server /usr/src/app

RUN adduser -D userapp

USER userapp

ENV PORT=8000 REQUEST_ORIGIN=http://localhost:5000

EXPOSE ${PORT}

CMD ./server