FROM node:15.14.0-alpine3.10

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm install -g serve

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://localhost:8000

RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]