version: '3.7'

# Assuming the two Dockerfiles from exercise 1.14 are in each project's directory (both unmodified since that exercise)
services:
    redis:
        image: "redis:alpine"
        restart: unless-stopped
    backend:
        build: ./example-backend
        ports:
            - "8000:8000"
        environment:
            - REDIS_HOST=redis
    frontend:
        build: ./example-frontend
        ports:
            - "5000:5000"